# pdf_generator.py

from fpdf import FPDF
from datetime import datetime
import os


# ---------- PDF text sanitizer (FPDF needs latin-1) ----------
def _pdf_safe_text(s):
    """
    Convert/replace common unicode chars that FPDF (latin-1) can't encode.
    Use this on any text written into the PDF.
    """
    if s is None:
        return ""

    s = str(s)
    replacements = {
        "\u2014": "-",  # em dash
        "\u2013": "-",  # en dash
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2026": "...",
    }

    for k, v in replacements.items():
        s = s.replace(k, v)

    return s.encode("latin-1", errors="replace").decode("latin-1")


# ---------- Custom PDF class ----------
class ProfessionalPDF(FPDF):
    def header(self):
        pass


# ---------- Main PDF Generator ----------
def generate_professional_pdf(
    patient_details,
    disease_type,
    params_with_ranges,
    result_text,
    risk_score=None,
    risk_category=None,
    reference_ranges=None,
    advice_text=None,
    output_dir="reports"
):
    """
    params_with_ranges: list of tuples (name, value, note)
    reference_ranges: dict mapping param_name -> expected range string
    """

    pdf = ProfessionalPDF('P', 'mm', 'A4')
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()

    # ---------------- HEADER BAR ----------------
    pdf.set_fill_color(0, 85, 155)
    pdf.rect(0, 0, 210, 22, 'F')

    pdf.set_xy(10, 5)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", "B", 18)
    pdf.cell(190, 12, _pdf_safe_text("AI Doctor Diagnostic Report"), ln=True, align='C')

    pdf.ln(8)

    # ---------------- PATIENT DETAILS ----------------
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, _pdf_safe_text("Patient Details"), ln=1)

    pdf.set_font("Arial", size=11)
    pdf.ln(1)

    def info(label, value):
        pdf.set_font("Arial", "B", 11)
        pdf.cell(35, 7, _pdf_safe_text(label), ln=0)
        pdf.set_font("Arial", size=11)
        pdf.cell(90, 7, _pdf_safe_text(str(value)), ln=1)

    info("Name:", patient_details.get("Name", ""))
    info("Age:", patient_details.get("Age", ""))
    info("Gender:", patient_details.get("Gender", ""))
    info("Phone:", patient_details.get("Phone", ""))

    pdf.ln(4)

    # ---------------- TEST SECTION ----------------
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, _pdf_safe_text(f"Test: {disease_type}"), ln=1)

    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 7, _pdf_safe_text(f"Prediction Result: {result_text}"))
    pdf.ln(3)

    # ---------------- RISK SECTION (NEW) ----------------
    if risk_score is not None and risk_category is not None:

        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "AI Risk Analysis", ln=1)

        pdf.set_font("Arial", size=11)

        pdf.cell(0, 7, _pdf_safe_text(f"Risk Score: {risk_score}%"), ln=1)
        pdf.cell(0, 7, _pdf_safe_text(f"Risk Category: {risk_category}"), ln=1)

        pdf.ln(4)

    # ---------------- PARAMETERS TABLE ----------------
    pdf.set_font("Arial", "B", 11)
    col_w = [60, 40, 85]

    pdf.set_fill_color(225, 225, 225)
    pdf.cell(col_w[0], 9, "Parameter", border=1, align="C", fill=True)
    pdf.cell(col_w[1], 9, "Value", border=1, align="C", fill=True)
    pdf.cell(col_w[2], 9, "Note", border=1, ln=1, align="C", fill=True)

    pdf.set_font("Arial", size=10)

    fill = False
    for (name, val, note) in params_with_ranges:
        pdf.set_fill_color(245 if fill else 255, 245, 245)
        fill = not fill

        pdf.cell(col_w[0], 8, _pdf_safe_text(str(name)), border=1, fill=fill)
        pdf.cell(col_w[1], 8, _pdf_safe_text(str(val)), border=1, fill=fill)
        pdf.cell(col_w[2], 8, _pdf_safe_text(str(note)), border=1, ln=1, fill=fill)

    pdf.ln(6)

    # ---------------- REFERENCE RANGES ----------------
    if reference_ranges:
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, "Reference / Expected Ranges", ln=1)

        pdf.set_font("Arial", size=10)
        for k, v in reference_ranges.items():
            pdf.multi_cell(0, 6, _pdf_safe_text(f"- {k}: {v}"))
        pdf.ln(4)

    # ---------------- ADVICE SECTION ----------------
    if advice_text:
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, "Advice & Next Steps", ln=1)

        pdf.set_font("Arial", size=10)
        pdf.multi_cell(0, 6, _pdf_safe_text(advice_text))
        pdf.ln(4)

    # ---------------- FOOTER ----------------
    pdf.set_font("Arial", "I", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(
        0,
        6,
        _pdf_safe_text(
            "Generated by AI Doctor — This is an AI-based screening report, "
            "not a substitute for professional medical diagnosis."
        ),
    )

    # ---------------- SAVE FILE ----------------
    os.makedirs(output_dir, exist_ok=True)

    safe_name = (patient_details.get("Name", "patient") or "patient").replace(" ", "_")
    fname = f"{safe_name}_{disease_type}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    output_path = os.path.join(output_dir, fname)

    pdf.output(output_path)

    return output_path